name: Build and deploy ASP.Net Core app to Azure Web App - timingapplite

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest





























    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.x'

      - name: Install AOT prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y clang binutils

      - name: Publish with AOT
        run: >
          dotnet publish DotNetBackend/DotNetBackend/DotNetBackend.csproj
          -c Release
          --self-contained
          -r linux-x64
          -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v7
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v8
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_79C5FA2FD03A4509B08BD3AF63ABE952 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E454D3DE4FD3412FAEAEBE530335E457 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_666ABE017D2840B8B364E6DE59141B69 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'timingapplite'
          slot-name: 'Production'
          package: .