name: Trigger auto deployment for timingapplite

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/timingapplite-AutoDeployTrigger-40268da8-4efa-4907-827a-1b54e0fa9baa.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
      packages: write #Required to push to GitHub Container Registry

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.TIMINGAPPLITE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TIMINGAPPLITE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TIMINGAPPLITE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy to Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/DotNetBackend
          dockerfilePath: Dockerfile
          registryUrl: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GITHUB_TOKEN }}
          containerAppName: timingapplite
          resourceGroup: AutoTest
          imageToBuild: ghcr.io/${{ github.repository_owner }}/timingapplite:${{ github.sha }}


